numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py

Start time:  2024-07-19 19:21:15.784547
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_netParams.py

Creating network of 43 cell populations on 128 hosts...
  Number of cells on node 62: 53 
  Number of cells on node 23: 53 
  Number of cells on node 26: 53 
  Number of cells on node 93: 53 
  Number of cells on node 45: 53 
  Number of cells on node 18: 53 
  Number of cells on node 13: 53 
  Number of cells on node 4: 54 
  Number of cells on node 27: 53 
  Number of cells on node 119: 53 
  Number of cells on node 52: 53 
  Number of cells on node 42: 53 
  Number of cells on node 65: 53 
  Number of cells on node 1: 54 
  Number of cells on node 64: 53 
  Number of cells on node 10: 54 
  Number of cells on node 110: 53 
  Number of cells on node 69: 53 
  Number of cells on node 40: 53 
  Number of cells on node 103: 53 
  Number of cells on node 96: 53 
  Number of cells on node 107: 53 
  Number of cells on node 67: 53 
  Number of cells on node 88: 53 
  Number of cells on node 90: 53 
  Number of cells on node 113: 53 
  Number of cells on node 102: 53 
  Number of cells on node 24: 53 
  Number of cells on node 60: 53 
  Number of cells on node 100: 53 
  Number of cells on node 36: 53 
  Number of cells on node 81: 53 
  Number of cells on node 101: 53 
  Number of cells on node 98: 53 
  Number of cells on node 115: 53 
  Number of cells on node 31: 53 
  Number of cells on node 80: 53 
  Number of cells on node 11: 54 
  Number of cells on node 25: 53 
  Number of cells on node 28: 53 
  Number of cells on node 122: 53 
  Number of cells on node 59: 53 
  Number of cells on node 51: 53 
  Number of cells on node 38: 53 
  Number of cells on node 89: 53 
  Number of cells on node 126: 53 
  Number of cells on node 95: 53 
  Number of cells on node 44: 53 
  Number of cells on node 123: 53 
  Number of cells on node 125: 53 
  Number of cells on node 49: 53 
  Number of cells on node 7: 54 
  Number of cells on node 118: 53 
  Number of cells on node 71: 53 
  Number of cells on node 3: 54 
  Number of cells on node 97: 53 
  Number of cells on node 39: 53 
  Number of cells on node 55: 53 
  Number of cells on node 57: 53 
  Number of cells on node 56: 53 
  Number of cells on node 16: 53 
  Number of cells on node 34: 53 
  Number of cells on node 70: 53 
  Number of cells on node 29: 53 
  Number of cells on node 75: 53 
  Number of cells on node 58: 53 
  Number of cells on node 2: 54 
  Number of cells on node 85: 53 
  Number of cells on node 104: 53 
  Number of cells on node 78: 53 
  Number of cells on node 127: 53 
  Number of cells on node 87: 53 
  Number of cells on node 41: 53 
  Number of cells on node 22: 53 
  Number of cells on node 14: 53 
  Number of cells on node 68: 53 
  Number of cells on node 116: 53 
  Number of cells on node 84: 53 
  Number of cells on node 50: 53 
  Number of cells on node 32: 53 
  Number of cells on node 120: 53 
  Number of cells on node 92: 53 
  Number of cells on node 35: 53 
  Number of cells on node 0: 54 
  Number of cells on node 47: 53 
  Number of cells on node 9: 54 
  Number of cells on node 20: 53 
  Number of cells on node 79: 53 
  Number of cells on node 111: 53 
  Number of cells on node 112: 53 
  Number of cells on node 37: 53 
  Number of cells on node 21: 53 
  Number of cells on node 66: 53 
  Number of cells on node 83: 53 
  Number of cells on node 121: 53 
  Number of cells on node 86: 53 
  Number of cells on node 91: 53 
  Number of cells on node 30: 53 
  Number of cells on node 106: 53 
  Number of cells on node 63: 53 
  Number of cells on node 54: 53 
  Number of cells on node 53: 53 
  Number of cells on node 82: 53 
  Number of cells on node 105: 53 
  Number of cells on node 124: 53 
  Number of cells on node 6: 54 
  Number of cells on node 99: 53 
  Number of cells on node 33: 53 
  Number of cells on node 77: 53 
  Number of cells on node 76: 53 
  Number of cells on node 48: 53 
  Number of cells on node 46: 53 
  Number of cells on node 74: 53 
  Number of cells on node 114: 53 
  Number of cells on node 61: 53 
  Number of cells on node 109: 53 
  Number of cells on node 108: 53 
  Number of cells on node 72: 53 
  Number of cells on node 15: 53 
  Number of cells on node 19: 53 
  Number of cells on node 12: 53 
  Number of cells on node 8: 54 
  Number of cells on node 43: 53 
  Number of cells on node 73: 53 
  Number of cells on node 17: 53 
  Number of cells on node 94: 53 
  Number of cells on node 5: 54 
  Number of cells on node 117: 53 
  Done; cell creation time = 9.24 s.
Making connections...
  Number of connections on node 50: 8745 
  Number of synaptic contacts on node 50: 41385 
  Number of connections on node 42: 9077 
  Number of synaptic contacts on node 42: 42932 
  Number of connections on node 58: 9036 
  Number of synaptic contacts on node 58: 43063 
  Number of connections on node 26: 8581 
  Number of synaptic contacts on node 26: 40144 
  Number of connections on node 0: 8655 
  Number of synaptic contacts on node 0: 39700 
  Number of connections on node 8: 8842 
  Number of synaptic contacts on node 8: 40912 
  Number of connections on node 2: 9005 
  Number of synaptic contacts on node 2: 41902 
  Number of connections on node 40: 8882 
  Number of synaptic contacts on node 40: 41745 
  Number of connections on node 10: 9055 
  Number of synaptic contacts on node 10: 41957 
  Number of connections on node 48: 9185 
  Number of synaptic contacts on node 48: 43618 
  Number of connections on node 16: 9147 
  Number of synaptic contacts on node 16: 42870 
  Number of connections on node 56: 8853 
  Number of synaptic contacts on node 56: 42745 
  Number of connections on node 24: 9071 
  Number of synaptic contacts on node 24: 42372 
  Number of connections on node 18: 8866 
  Number of synaptic contacts on node 18: 41146 
  Number of connections on node 34: 8823 
  Number of synaptic contacts on node 34: 41200 
  Number of connections on node 32: 8824 
  Number of synaptic contacts on node 32: 41289 
  Number of connections on node 65: 8853 
  Number of synaptic contacts on node 65: 42170 
  Number of connections on node 1: 8828 
  Number of synaptic contacts on node 1: 40193 
  Number of connections on node 106: 9226 
  Number of synaptic contacts on node 106: 42746 
  Number of connections on node 22: 8538 
  Number of synaptic contacts on node 22: 39931 
  Number of connections on node 36: 8808 
  Number of synaptic contacts on node 36: 41165 
  Number of connections on node 121: 8842 
  Number of synaptic contacts on node 121: 40796 
  Number of connections on node 25: 8954 
  Number of synaptic contacts on node 25: 41590 
  Number of connections on node 105: 9133 
  Number of synaptic contacts on node 105: 43022 
  Number of connections on node 17: 9186 
  Number of synaptic contacts on node 17: 42114 
  Number of connections on node 9: 9025 
  Number of synaptic contacts on node 9: 42103 
  Number of connections on node 123: 8598 
  Number of synaptic contacts on node 123: 39517 
  Number of connections on node 96: 8926 
  Number of synaptic contacts on node 96: 41833 
  Number of connections on node 4: 8873 
  Number of synaptic contacts on node 4: 40852 
  Number of connections on node 3: 8738 
  Number of synaptic contacts on node 3: 40157 
  Number of connections on node 90: 9113 
  Number of synaptic contacts on node 90: 43531 
  Number of connections on node 113: 8554 
  Number of synaptic contacts on node 113: 39568 
  Number of connections on node 72: 8875 
  Number of synaptic contacts on node 72: 42190 
  Number of connections on node 74: 9034 
  Number of synaptic contacts on node 74: 42952 
  Number of connections on node 35: 8774 
  Number of synaptic contacts on node 35: 41257 
  Number of connections on node 46: 8878 
  Number of synaptic contacts on node 46: 42260 
  Number of connections on node 19: 8876 
  Number of synaptic contacts on node 19: 41219 
  Number of connections on node 107: 9264 
  Number of synaptic contacts on node 107: 43245 
  Number of connections on node 115: 9111 
  Number of synaptic contacts on node 115: 41815 
  Number of connections on node 104: 9033 
  Number of synaptic contacts on node 104: 42245 
  Number of connections on node 122: 8669 
  Number of synaptic contacts on node 122: 39732 
  Number of connections on node 20: 8747 
  Number of synaptic contacts on node 20: 41123 
  Number of connections on node 98: 9235 
  Number of synaptic contacts on node 98: 42663 
  Number of connections on node 60: 8618 
  Number of synaptic contacts on node 60: 40351 
  Number of connections on node 99: 9100 
  Number of synaptic contacts on node 99: 42301 
  Number of connections on node 91: 8727 
  Number of synaptic contacts on node 91: 40795 
  Number of connections on node 38: 8864 
  Number of synaptic contacts on node 38: 42134 
  Number of connections on node 97: 9256 
  Number of synaptic contacts on node 97: 43026 
  Number of connections on node 114: 8752 
  Number of synaptic contacts on node 114: 40695 
  Number of connections on node 54: 8754 
  Number of synaptic contacts on node 54: 40927 
  Number of connections on node 81: 8954 
  Number of synaptic contacts on node 81: 41823 
  Number of connections on node 75: 9011 
  Number of synaptic contacts on node 75: 42606 
  Number of connections on node 66: 9130 
  Number of synaptic contacts on node 66: 43267 
  Number of connections on node 41: 8761 
  Number of synaptic contacts on node 41: 41233 
  Number of connections on node 82: 8961 
  Number of synaptic contacts on node 82: 42186 
  Number of connections on node 11: 9232 
  Number of synaptic contacts on node 11: 42861 
  Number of connections on node 30: 9260 
  Number of synaptic contacts on node 30: 43126 
  Number of connections on node 64: 8902 
  Number of synaptic contacts on node 64: 41912 
  Number of connections on node 51: 8926 
  Number of synaptic contacts on node 51: 42168 
  Number of connections on node 44: 9242 
  Number of synaptic contacts on node 44: 44290 
  Number of connections on node 49: 9203 
  Number of synaptic contacts on node 49: 43900 
  Number of connections on node 12: 8962 
  Number of synaptic contacts on node 12: 41607 
  Number of connections on node 28: 8790 
  Number of synaptic contacts on node 28: 40767 
  Number of connections on node 27: 8918 
  Number of synaptic contacts on node 27: 41790 
  Number of connections on node 88: 9129 
  Number of synaptic contacts on node 88: 42949 
  Number of connections on node 33: 8929 
  Number of synaptic contacts on node 33: 42071 
  Number of connections on node 62: 8914 
  Number of synaptic contacts on node 62: 42250 
  Number of connections on node 67: 8748 
  Number of synaptic contacts on node 67: 41320 
  Number of connections on node 59: 9074 
  Number of synaptic contacts on node 59: 43150 
  Number of connections on node 112: 9019 
  Number of synaptic contacts on node 112: 42182 
  Number of connections on node 120: 8540 
  Number of synaptic contacts on node 120: 39343 
  Number of connections on node 73: 9029 
  Number of synaptic contacts on node 73: 43018 
  Number of connections on node 83: 9185 
  Number of synaptic contacts on node 83: 43916 
  Number of connections on node 6: 9058 
  Number of synaptic contacts on node 6: 41363 
  Number of connections on node 43: 8750 
  Number of synaptic contacts on node 43: 41825 
  Number of connections on node 57: 8820 
  Number of synaptic contacts on node 57: 42423 
  Number of connections on node 89: 8731 
  Number of synaptic contacts on node 89: 41437 
  Number of connections on node 14: 8721 
  Number of synaptic contacts on node 14: 40500 
  Number of connections on node 52: 9143 
  Number of synaptic contacts on node 52: 43992 
  Number of connections on node 80: 9101 
  Number of synaptic contacts on node 80: 43870 
  Number of connections on node 71: 8914 
  Number of synaptic contacts on node 71: 42006 
  Number of connections on node 94: 9180 
  Number of synaptic contacts on node 94: 42404 
  Number of connections on node 95: 9041 
  Number of synaptic contacts on node 95: 41824 
  Number of connections on node 37: 9141 
  Number of synaptic contacts on node 37: 43444 
  Number of connections on node 124: 8507 
  Number of synaptic contacts on node 124: 39165 
  Number of connections on node 119: 8808 
  Number of synaptic contacts on node 119: 40831 
  Number of connections on node 125: 8915 
  Number of synaptic contacts on node 125: 40937 
  Number of connections on node 53: 8926 
  Number of synaptic contacts on node 53: 42053 
  Number of connections on node 78: 9053 
  Number of synaptic contacts on node 78: 43536 
  Number of connections on node 126: 8247 
  Number of synaptic contacts on node 126: 38358 
  Number of connections on node 103: 9153 
  Number of synaptic contacts on node 103: 42094 
  Number of connections on node 55: 9174 
  Number of synaptic contacts on node 55: 43247 
  Number of connections on node 29: 8614 
  Number of synaptic contacts on node 29: 40312 
  Number of connections on node 39: 9022 
  Number of synaptic contacts on node 39: 42433 
  Number of connections on node 127: 8749 
  Number of synaptic contacts on node 127: 40349 
  Number of connections on node 87: 8982 
  Number of synaptic contacts on node 87: 42153 
  Number of connections on node 47: 8867 
  Number of synaptic contacts on node 47: 42768 
  Number of connections on node 5: 8666 
  Number of synaptic contacts on node 5: 40012 
  Number of connections on node 13: 8983 
  Number of synaptic contacts on node 13: 42027 
  Number of connections on node 31: 8721 
  Number of synaptic contacts on node 31: 41579 
  Number of connections on node 15: 9306 
  Number of synaptic contacts on node 15: 42962 
  Number of connections on node 61: 9090 
  Number of connections on node 21: 8805 
  Number of synaptic contacts on node 21: 41707 
  Number of synaptic contacts on node 61: 43164 
  Number of connections on node 23: 8878 
  Number of synaptic contacts on node 23: 41328 
  Number of connections on node 111: 9425 
  Number of synaptic contacts on node 111: 43591 
  Number of connections on node 92: 9148 
  Number of synaptic contacts on node 92: 42559 
  Number of connections on node 100: 8997 
  Number of synaptic contacts on node 100: 42080 
  Number of connections on node 102: 9432 
  Number of synaptic contacts on node 102: 44223 
  Number of connections on node 79: 8666 
  Number of synaptic contacts on node 79: 40828 
  Number of connections on node 76: 9041 
  Number of synaptic contacts on node 76: 43304 
  Number of connections on node 7: 8875 
  Number of synaptic contacts on node 7: 41350 
  Number of connections on node 70: 9153 
  Number of synaptic contacts on node 70: 43544 
  Number of connections on node 93: 9042 
  Number of synaptic contacts on node 93: 42472 
  Number of connections on node 86: 8875 
  Number of synaptic contacts on node 86: 41597 
  Number of connections on node 85: 8891 
  Number of synaptic contacts on node 85: 42098 
  Number of connections on node 118: 8746 
  Number of synaptic contacts on node 118: 40574 
  Number of connections on node 68: 9118 
  Number of synaptic contacts on node 68: 43492 
  Number of connections on node 63: 8659 
  Number of synaptic contacts on node 63: 41312 
  Number of connections on node 69: 9113 
  Number of synaptic contacts on node 69: 43167 
  Number of connections on node 101: 9075 
  Number of synaptic contacts on node 101: 42557 
  Number of connections on node 110: 9221 
  Number of synaptic contacts on node 110: 43372 
  Number of connections on node 109: 9127 
  Number of synaptic contacts on node 109: 41989 
  Number of connections on node 117: 8891 
  Number of synaptic contacts on node 117: 40819 
  Number of connections on node 45: 9159 
  Number of synaptic contacts on node 45: 43921 
  Number of connections on node 77: 9003 
  Number of synaptic contacts on node 77: 42545 
  Number of connections on node 116: 8745 
  Number of synaptic contacts on node 116: 40917 
  Number of connections on node 108: 8895 
  Number of synaptic contacts on node 108: 41084 
  Number of connections on node 84: 8912 
  Number of synaptic contacts on node 84: 41655 
  Done; cell connection time = 338.01 s.
Adding stims...
  Number of stims on node 67: 530 
  Number of stims on node 65: 530 
  Number of stims on node 75: 530 
  Number of stims on node 73: 530 
  Number of stims on node 123: 530 
  Number of stims on node 63: 530 
  Number of stims on node 113: 530 
  Number of stims on node 60: 530 
  Number of stims on node 56: 530 
  Number of stims on node 96: 530 
  Number of stims on node 50: 530 
  Number of stims on node 62: 530 
  Number of stims on node 51: 530 
  Number of stims on node 57: 530 
  Number of stims on node 99: 530 
  Number of stims on node 42: 530 
  Number of stims on node 98: 530 
  Number of stims on node 17: 530 
  Number of stims on node 83: 530 
  Number of stims on node 109: 530 
  Number of stims on node 69: 530 
  Number of stims on node 68: 530 
  Number of stims on node 49: 530 
  Number of stims on node 54: 530 
  Number of stims on node 80: 530 
  Number of stims on node 100: 530 
  Number of stims on node 102: 530 
  Number of stims on node 107: 530 
  Number of stims on node 52: 530 
  Number of stims on node 77: 530 
  Number of stims on node 64: 530 
  Number of stims on node 111: 530 
  Number of stims on node 85: 530 
  Number of stims on node 89: 530 
  Number of stims on node 82: 530 
  Number of stims on node 34: 530 
  Number of stims on node 79: 530 
  Number of stims on node 78: 530 
  Number of stims on node 48: 530 
  Number of stims on node 32: 530 
  Number of stims on node 46: 530 
  Number of stims on node 59: 530 
  Number of stims on node 91: 530 
  Number of stims on node 9: 540 
  Number of stims on node 117: 530 
  Number of stims on node 126: 530 
  Number of stims on node 28: 530 
  Number of stims on node 43: 530 
  Number of stims on node 23: 530 
  Number of stims on node 26: 530 
  Number of stims on node 93: 530 
  Number of stims on node 105: 530 
  Number of stims on node 41: 530 
  Number of stims on node 58: 530 
  Number of stims on node 35: 530 
  Number of stims on node 127: 530 
  Number of stims on node 114: 530 
  Number of stims on node 92: 530 
  Number of stims on node 121: 530 
  Number of stims on node 44: 530 
  Number of stims on node 55: 530 
  Number of stims on node 0: 540 
  Number of stims on node 103: 530 
  Number of stims on node 47: 530 
  Number of stims on node 120: 530 
  Number of stims on node 2: 540 
  Number of stims on node 87: 530 
  Number of stims on node 70: 530 
  Number of stims on node 106: 530 
  Number of stims on node 8: 540 
  Number of stims on node 115: 530 
  Number of stims on node 66: 530 
  Number of stims on node 97: 530 
  Number of stims on node 84: 530 
  Number of stims on node 81: 530 
  Number of stims on node 45: 530 
  Number of stims on node 3: 540 
  Number of stims on node 10: 540 
  Number of stims on node 112: 530 
  Number of stims on node 19: 530 
  Number of stims on node 72: 530 
  Number of stims on node 94: 530 
  Number of stims on node 110: 530 
  Number of stims on node 14: 530 
  Number of stims on node 18: 530 
  Number of stims on node 122: 530 
  Number of stims on node 24: 530 
  Number of stims on node 30: 530 
  Number of stims on node 101: 530 
  Number of stims on node 88: 530 
  Number of stims on node 124: 530 
  Number of stims on node 1: 540 
  Number of stims on node 74: 530 
  Number of stims on node 12: 530 
  Number of stims on node 21: 530 
  Number of stims on node 95: 530 
  Number of stims on node 11: 540 
  Number of stims on node 104: 530 
  Number of stims on node 118: 530 
  Number of stims on node 25: 530 
  Number of stims on node 27: 530 
  Number of stims on node 7: 540 
  Number of stims on node 36: 530 
  Number of stims on node 15: 530 
  Number of stims on node 116: 530 
  Number of stims on node 29: 530 
  Number of stims on node 16: 530 
  Number of stims on node 90: 530 
  Number of stims on node 13: 530 
  Number of stims on node 108: 530 
  Number of stims on node 33: 530 
  Number of stims on node 40: 530 
  Number of stims on node 76: 530 
  Number of stims on node 22: 530 
  Number of stims on node 125: 530 
  Number of stims on node 119: 530 
  Number of stims on node 71: 530 
  Number of stims on node 39: 530 
  Number of stims on node 61: 530 
  Number of stims on node 53: 530 
  Number of stims on node 6: 540 
  Number of stims on node 20: 530 
  Number of stims on node 38: 530 
  Number of stims on node 4: 540 
  Number of stims on node 31: 530 
  Number of stims on node 37: 530 
  Number of stims on node 86: 530 
  Number of stims on node 5: 540 
  Done; cell stims creation time = 1.14 s.
Recording 0 traces of 0 types on node 73
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 64
Recording 0 traces of 0 types on node 83
Recording 0 traces of 0 types on node 74
Recording 0 traces of 0 types on node 34
Recording 0 traces of 0 types on node 35
Recording 0 traces of 0 types on node 65
Recording 0 traces of 0 types on node 57
Recording 6 traces of 6 types on node 0
Recording 0 traces of 0 types on node 67
Recording 0 traces of 0 types on node 99
Recording 0 traces of 0 types on node 75
Recording 6 traces of 6 types on node 98
Recording 0 traces of 0 types on node 72
Recording 0 traces of 0 types on node 66
Recording 0 traces of 0 types on node 49
Recording 6 traces of 6 types on node 3
Recording 0 traces of 0 types on node 100
Recording 0 traces of 0 types on node 44
Recording 0 traces of 0 types on node 115
Recording 6 traces of 6 types on node 48
Recording 6 traces of 6 types on node 126
Recording 12 traces of 6 types on node 1
Recording 0 traces of 0 types on node 123
Recording 0 traces of 0 types on node 109
Recording 6 traces of 6 types on node 40
Recording 0 traces of 0 types on node 108
Recording 0 traces of 0 types on node 55
Recording 0 traces of 0 types on node 95
Recording 0 traces of 0 types on node 68
Recording 6 traces of 6 types on node 30
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 29
Recording 6 traces of 6 types on node 12
Recording 12 traces of 6 types on node 26
Recording 6 traces of 6 types on node 94
Recording 0 traces of 0 types on node 63
Recording 0 traces of 0 types on node 45
Recording 0 traces of 0 types on node 62
Recording 0 traces of 0 types on node 46
Recording 18 traces of 6 types on node 31
Recording 6 traces of 6 types on node 41
Recording 6 traces of 6 types on node 125
Recording 0 traces of 0 types on node 85
Recording 0 traces of 0 types on node 111
Recording 6 traces of 6 types on node 79
Recording 0 traces of 0 types on node 70
Recording 0 traces of 0 types on node 16
Recording 12 traces of 6 types on node 9
Recording 6 traces of 6 types on node 122
Recording 6 traces of 6 types on node 24
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 54
Recording 0 traces of 0 types on node 103
Recording 0 traces of 0 types on node 69
Recording 0 traces of 0 types on node 61
Recording 0 traces of 0 types on node 82
Recording 0 traces of 0 types on node 71
Recording 12 traces of 6 types on node 60
Recording 0 traces of 0 types on node 118
Recording 0 traces of 0 types on node 36
Recording 0 traces of 0 types on node 112
Recording 6 traces of 6 types on node 90
Recording 0 traces of 0 types on node 5
Recording 6 traces of 6 types on node 107
Recording 0 traces of 0 types on node 120
Recording 12 traces of 6 types on node 51
Recording 12 traces of 6 types on node 105
Recording 6 traces of 6 types on node 121
Recording 18 traces of 6 types on node 114
Recording 6 traces of 6 types on node 50
Recording 12 traces of 6 types on node 43
Recording 0 traces of 0 types on node 116
Recording 12 traces of 6 types on node 80
Recording 6 traces of 6 types on node 13
Recording 0 traces of 0 types on node 58
Recording 6 traces of 6 types on node 11
Recording 0 traces of 0 types on node 25
Recording 12 traces of 6 types on node 52
Recording 6 traces of 6 types on node 4
Recording 0 traces of 0 types on node 104
Recording 0 traces of 0 types on node 88
Recording 6 traces of 6 types on node 18
Recording 12 traces of 6 types on node 42
Recording 6 traces of 6 types on node 97
Recording 0 traces of 0 types on node 33
Recording 0 traces of 0 types on node 22
Recording 6 traces of 6 types on node 37
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 117
Recording 0 traces of 0 types on node 102
Recording 6 traces of 6 types on node 59
Recording 12 traces of 6 types on node 32
Recording 6 traces of 6 types on node 47
Recording 6 traces of 6 types on node 93
Recording 0 traces of 0 types on node 96
Recording 12 traces of 6 types on node 124
Recording 6 traces of 6 types on node 87
Recording 12 traces of 6 types on node 81
Recording 0 traces of 0 types on node 110
Recording 6 traces of 6 types on node 10
Recording 0 traces of 0 types on node 15
Recording 6 traces of 6 types on node 6
Recording 0 traces of 0 types on node 14
Recording 6 traces of 6 types on node 8
Recording 0 traces of 0 types on node 119
Recording 12 traces of 6 types on node 7
Recording 12 traces of 6 types on node 38
Recording 12 traces of 6 types on node 113
Recording 6 traces of 6 types on node 53
Recording 12 traces of 6 types on node 20
Recording 6 traces of 6 types on node 89
Recording 12 traces of 6 types on node 39
Recording 12 traces of 6 types on node 106
Recording 6 traces of 6 types on node 91
Recording 12 traces of 6 types on node 77
Recording 0 traces of 0 types on node 78
Recording 0 traces of 0 types on node 101
Recording 6 traces of 6 types on node 86
Recording 12 traces of 6 types on node 19
Recording 6 traces of 6 types on node 21
Recording 0 traces of 0 types on node 84
Recording 12 traces of 6 types on node 27
Recording 6 traces of 6 types on node 92
Recording 12 traces of 6 types on node 76
Recording 6 traces of 6 types on node 127
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
Applying TMS to network...
0.0s

Running simulation using NEURON for 5000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
  Done; run time = 47840.63 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.02 s.

Analyzing...
  Cells: 6796
  Connections: 0 (0.00 per cell)
  Spikes: 40958 (1.21 Hz)
  Simulated time: 5.0 s; 128 workers
  Run time: 47840.63 s
   L1_DAC_bNA : 0.820 Hz
   L1_DAC_cNA : 0.000 Hz
   L1_DLAC_cNA : 0.000 Hz
   L23_MC_bAC : 0.000 Hz
   L23_MC_bNA : 0.000 Hz
   L23_MC_cAC : 0.000 Hz
   L23_MC_cNA : 0.000 Hz
   L23_MC_dNA : 0.000 Hz
   L23_PC_cAD : 0.050 Hz
   L23_SBC_bNA : 1.920 Hz
   L23_SBC_cAC : 0.160 Hz
   L23_SBC_dNA : 1.739 Hz
   L4_MC_bAC : 0.200 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.000 Hz
   L4_MC_cNA : 7.000 Hz
   L4_MC_dNA : 6.000 Hz
   L4_PC_cAD : 1.690 Hz
   L4_SBC_bNA : 16.000 Hz
   L4_SBC_cAC : 12.491 Hz
   L4_SBC_dNA : 28.333 Hz
   L5_MC_bAC : 0.008 Hz
   L5_MC_bIR : 0.000 Hz
   L5_MC_bST : 0.000 Hz
   L5_MC_cAC : 0.000 Hz
   L5_MC_cNA : 15.550 Hz
   L5_MC_cST : 0.000 Hz
   L5_MC_dNA : 0.000 Hz
   L5_SBC_bNA : 21.200 Hz
   L5_SBC_cAC : 13.240 Hz
   L5_SBC_dNA : 33.300 Hz
   L5_TTPC2_cAD : 2.563 Hz
   L6_MC_bAC : 0.200 Hz
   L6_MC_bIR : 0.093 Hz
   L6_MC_bNA : 0.571 Hz
   L6_MC_bST : 0.343 Hz
   L6_MC_cAC : 0.009 Hz
   L6_MC_cIR : 0.000 Hz
   L6_MC_cNA : 3.171 Hz
   L6_SBC_bNA : 27.467 Hz
   L6_SBC_cAC : 21.667 Hz
   L6_SBC_dNA : 33.240 Hz
   L6_TPC_L4_cAD : 1.484 Hz
Saving output as /expanse/lustre/projects/csd403/fborges/v1_batch5/v1_batch5_0_data.pkl ... 
Finished saving!
  Done; saving time = 16.89 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 74.29 s

Total time = 48316.86 s
